services:
  sdc-backend-service:
    container_name: tic-tac-toe-engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/play/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
